name: Build And Prettify

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container: wpilib/roborio-cross-ubuntu:2025-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.1"

      - name: Install Packages
        run: npm ci

      - name: Check formatting
        run: npm run check